# Generated by Django 6.0.5 on 2026-06-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('season', models.IntegerField()),
                ('games', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0.0)),
                ('hr', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('ops', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-avg'],
                'unique_together': {('name', 'team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('season', models.IntegerField()),
                ('games', models.IntegerField(default=0)),
                ('era', models.FloatField(default=0.0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('whip', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['era'],
                'unique_together': {('name', 'team', 'season')},
            },
        ),
    ]
