# Generated by Django 6.0.5 on 2026-06-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('game_diff', models.CharField(default='0', max_length=10)),
                ('last10', models.CharField(default='', max_length=20)),
                ('streak', models.CharField(default='', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('season', 'team')},
            },
        ),
    ]
